# Generated by Django 4.2.7 on 2023-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(default='image', max_length=30),
        ),
    ]
