# Generated by Django 4.2.7 on 2023-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia', '0004_article_binomial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_alt',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
