# Generated by Django 4.2.7 on 2023-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia', '0005_alter_article_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
    ]
